# roles/users/tasks/main.yml
---
- name: Add maxb user
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
  with_items: "{{ users }}"

- name: Setup authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  with_items: "{{ users }}"

- name: Ensure wheel group
  group:
    name: wheel
    state: present

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add sudoers users to wheel group
  user:
    name: "{{ item.name }}"
    groups: wheel
    append: yes
  with_items: "{{ users }}"
